# Steam Games Data Analysis & Recommendation System 

Introduction: The purpose of this project is to build a recommendation system for PC games using Steam data. We also visualize this data and answer several buisness questions such as:

    1. Which genres generate the most revenue?

    2. Games of which genres are played the most (by number of hours)?

    3. How well do positive ratings by users coorelate with the revenue generated by a game?

    4. How popular are games for which discounts are offerent as opposed to those for which none are offered?

# I. Data: Cleaning, Preprocessing & Visualizing

The data we'll use is taken from Kaggle: https://www.kaggle.com/datasets/fronkongames/steam-games-dataset

This dataset is fairly large: 122,6211 rows (games/rows) and 39 features (columns). We choose to work with the csv file instead of json since the data is mostly tabular. There are several problems with the data and we will spend a fair bit of time making the data usable. In particular:

    1. We'll drop certain features that don't give us useful information: like URLs. There are some games with zero users! We'll drop these.

    2. A few features have no values for most rows: we'll have to drop these as well.

    3. Several column names don't correspond with the values in the rows. i.e., there is a mismatch of column name and what values they contain.

    4. There might be duplicate games (this is likely because some game publishers release different versions of a game in different countries.)

Let's begin by loading the data and exploring what it looks like.

In [105]:
import pandas as pd

In [106]:
df = pd.read_csv('C:/Python/Data Science Projects/Data/games.csv')

In [107]:
df.info()

<class 'pandas.DataFrame'>
Index: 122611 entries, 2539430 to 4141790
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       122610 non-null  str
 1   Name                        122611 non-null  str
 2   Release date                122611 non-null  str
 3   Estimated owners            122611 non-null  int64
 4   Peak CCU                    122611 non-null  int64
 5   Required age                122611 non-null  float64
 6   Price                       122611 non-null  int64
 7   DiscountDLC count           122611 non-null  int64
 8   About the game              114162 non-null  str
 9   Supported languages         122611 non-null  str
 10  Full audio languages        122611 non-null  str
 11  Reviews                     12070 non-null   str
 12  Header image                122530 non-null  str
 13  Website                     49676 non-null   str
 14  Support url                 54142 non-null   str
 15  Support email               100348 non-null  str
 16  Windows                     122611 non-null  bool
 17  Mac                         122611 non-null  bool
 18  Linux                       122611 non-null  bool
 19  Metacritic score            122611 non-null  int64
 20  Metacritic url              4256 non-null    str
 21  User score                  122611 non-null  int64
 22  Positive                    122611 non-null  int64
 23  Negative                    122611 non-null  int64
 24  Score rank                  40 non-null      float64
 25  Achievements                122611 non-null  int64
 26  Recommendations             122611 non-null  int64
 27  Notes                       22458 non-null   str
 28  Average playtime forever    122611 non-null  int64
 29  Average playtime two weeks  122611 non-null  int64
 30  Median playtime forever     122611 non-null  int64
 31  Median playtime two weeks   122611 non-null  int64
 32  Developers                  114174 non-null  str
 33  Publishers                  113702 non-null  str
 34  Categories                  113658 non-null  str
 35  Genres                      114198 non-null  str
 36  Tags                        83346 non-null   str
 37  Screenshots                 116593 non-null  str
 38  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(14), str(19)
memory usage: 35.0 MB

In [108]:
df.shape

(122611, 39)

In [109]:
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

We observe that there are several issues with this dataset. For now we focus on the features.

1. The names of the first nine features (columns) are incorrectly aligned. In particular, the feature "DiscountDLC count" should be two separate features. 
2. While the feature AppID can serve as a unique datapoint (row) identifier, we will reindex the rows using positive integers.
3. We drop features don't contain useful data or sometimes, any data (NaN) at all. In particular, several features contain only URL that are of no use. 
4. We will repurpose some features and engineer new ones from old features.
5. Features like "Categories" and "Tags" are of utmost important for our recommender system and we will need to preprocess these features, among others.
6. Etcetra... 

We will address games (rows) at a later time.

Let's rename the columns so the first nine features actually match the data they're supposed to represent.

In [110]:
df.columns = ['Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'Discount', 'DLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

## Feature Engineering

**Feature Selection**: We begin by dropping features that will serve us no purpose. We list them below and provide brief reasoning for dropping them. 

1. **Required age**: We assume that any user of our recommender system is an adult. Moreover, this feature is highly unreliable: many game developers enter required age as "0" even though the game may contain elements that are inappropriate for younger gamers. Additionally, we don't intend to use this feature in any of our business analysis. To make up for the loss of this, we will drop games that contain undesired elements. See [Jump to Section](#Removing-games-with-undesired-elements)
2. **Discount**: This is the feature that was tangled up with its neighbor, "DLC count" and the dataset documentation on Kaggle simply does not give information on this feature. It could be interpreted in many ways: Is it the discount % of the game at the time the dataset was created, or is it the maximum discount the game has ever seen?, etc. As such, it is impossible to include this feature in any analysis and we therefore, reluctantly, drop it. 
3. **Full audio languages**: A list of audio languages a game supports. Niche or low budget indie games often cannot support audio in foreign languages. As such this feature is not an indicator of quality of a game, only its production budget. We will however use "Supported langauges" by coverting this feature into "Language count" that will give the number of langauges a given game supports. We intend to use this feature as a tie-breaker in our recommender system. 
4. **Website**: We will delete this feature that contains a lot of NaN fields. Instead we will create a new feature with the same name that will give the Steam webpage of a game in our recommender system.
5. **Support URL, Support email**: Links for owners of a game to get service and support. These features are not useful to us.
6. **Windows, Mac, Linux**: Boolean features telling us whether a game is supported for the given operating system. We notice below that almost all games are supported on Windows and there are only 32 games for Mac that don't run on Windows. As such, since most games are supported on Windows, we will simply get rid of these features. If our recommender ends up recommending a Linux only game to a Windows user, we trust the user will check the requirements to run the game on their computer.  
7. **Metacritic score, Metacritic url**: The vast majority of the feature "Metacritic score" is 0; this is a sparse feature. This means there is no data available. We can safely drop this feature. We also have no purpose of the corresponding URL feature.
8. **User score, user rank**: Note below that there are only 40 games that have non-zero "User score"; another sparse feature. We will also drop is statistically insignificant feature. This will affect the feature "Score rank" which is supposed to be a relative ranking of games based on "User score". As we see below, 'Score rank' contains no useful data and so we drop it as well.
10. **Average playtime two weeks, Median playtime two weeks**: These two features are less reliable than their "forever" counterparts. They measure a game's acitivity for a very short duration of time. As such, the "forever" playtime metrics are better indicators of a game's engagement and we therefore drop these inferior features.
11. **Achievements**: Gives the number of achievements a game offers. This number is highly unreliable. Many games offer a large number of achievements to attract gamers but the game itself lacks quality. On the other hand 100 achievements in Racing might be significaly easier (or harder) than 100 achievements in Puzzle or RPG games. As such, we don't see a way to meaningfully use this feature and therefore drop it.
12. **Screenshots**: A link to a game's screenshots. Not a useful feature for us.
13. **Movies**: Contains no data; all entries are NaN.

In [111]:
# Notice that many features are strings that are URL. Most of these are not useful to us.

df.iloc[0:5, 11:16]

,Reviews,Header image,Website,Support url,Support email
2539430,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN
496350,NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com
1034400,NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net
3292190,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com
3631080,NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com

In [112]:
# Most games run on Windows while the number of games that run on Mac or Linux but not on Windows is negligible. 

print((df['Windows'] == False).sum()) # Number of games that don't run on Windows.
print(df[(df['Linux'] == True) & (df['Windows'] == False)].shape[0]) # Number of Linux games that don't run on Windows. 
print(df[(df['Mac'] == True) & (df['Windows'] == False)].shape[0]) # Number of Mac games that don't run on Windows.

44
14
32

In [113]:
# A score of "0" for "Metacritic score" means that no data is available for that game. Most entries are zero. 

print((df['Metacritic score'] != 0).sum())

4256

In [114]:
# "User score" contains effectively no data. As a consequence, "Score rank" is a meaningless feature. 

print((df['User score'] != 0).sum())
print(df['Score rank'].nunique())

40
3

In [115]:
# The feature "Movies" contains no data.

print(df['Movies'].count())

0

**Dropping Features**: We now drop all columns we wish to at the same time and take a look at what our data now looks like. Note that we are not entirely done with dropping features. We will use certain features like "About the game", "Reviews" and "AppID" and then drop them once their usage is exhausted.

In [116]:
df = df.drop(columns = ['Required age', 'Discount', 'Full audio languages', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 
                   'User score', 'Score rank', 'Average playtime two weeks', 'Median playtime two weeks', 'Achievements', 'Screenshots', 'Movies']);

Let's add an index to the dataset and rename the first feature as "AppID", which is what the original index of the dataset is supposed to be. The App ID of a game is a unique number that identifies that game. We will use it below to create a new feature: the URL to the game's Steam webpage.

In [117]:
df = df.reset_index(drop = False) # Add a column that indexes the rows using positive integers.
df.index = df.index + 1

df = df.rename(columns={'index': 'AppID'}) # Rename the original index as "AppID".

In [118]:
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Price,DLC count,About the game,Supported languages,Reviews,...,Negative,Recommendations,Notes,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres,Tags
1,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0.00,0,NaN,[],NaN,...,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN
2,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,5.24,0,"Springtime, April: when the cherry trees come ...",['English'],NaN,...,3,231,NaN,8,8,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute"
3,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,4.99,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",NaN,...,3,0,NaN,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec..."
4,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,8.99,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],NaN,...,0,0,The game includes the following elements. 1. G...,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN
5,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],NaN,...,0,0,NaN,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN

### Data Preporcessing

**Duplicate Rows**: Let's start by checking if there are duplicate rows. Duplicate rows will have identical entires for each feature. The pandas function drop_duplicates() will keep one copy while tossing out the other duplicate ones.

In [119]:
n = df.duplicated().sum() # Number of duplicate rows.
print(f"There are {n} duplicate rows.")

df = df.drop_duplicates() # Our dataframe now contains no duplicate rows.

There are 0 duplicate rows.

We now take a look at each feature and prepare it for analysis.

In [120]:
df['Name'].describe()

count                                            122610
unique                                           121454
top       Shadow of the Tomb Raider: Definitive Edition
freq                                                 20
Name: Name, dtype: object

**Case Study 1: Dealing with duplicate Names**

There are games in the dataset with the exact same name. There are a few main reasons for this: 
1. The game was relased in a different region (and perhaps in a different language) of the world at a different time than its original release.
2. A slightly different version of the game was released (director's cut, extended edition, anniversary edition, remaster, etc.) but the name was the game was kept identical.
3. Several games could be named "Solitarie" but could be developed by different developers and as such, could be different games in terms of experience. 

We must decide how to handle this problem. There are two options:

    A. Keep the duplicates. The recommender will anyways be constructed to choose the best performing one, in case of a tie between two versions of a game with the same name.

    B. Keep only the best performing version: We could sort the games by metrics of performance: Peak CCU and/or Revenue (feature to be introduced below) and then we keep only the top version of the game. 

Decision: We keep the games with duplicate names. Note that these are not true duplicates: they differ in terms of other features. Moreover, all games have unique AppID and we will use this when recommending games. It is best not to throw out data unless absolutely necessary.

**Game with no Name**: Next, we check if there are any games with no name. As we see below, there is one, interestingly. We can use this game's AppID to visit the  [Steam webpage](https://store.steampowered.com/app/396420/_/) for this game and check that there indeed is no name for the game and the webpage is missing a lot of other information. We'll have to drop this game.

In [121]:
df[df['Name'].isnull()]

,AppID,Name,Release date,Estimated owners,Peak CCU,Price,DLC count,About the game,Supported languages,Reviews,...,Negative,Recommendations,Notes,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres,Tags
44433,396420,NaN,"Nov 1, 2016",0 - 0,0,0.0,0,Spookeningは3Dの恐怖ゲームで、あなたは毎夜に死んでゴーストとして復活します。 村...,[],NaN,...,0,0,NaN,0,0,NaN,NaN,NaN,NaN,NaN

In [122]:
df.dropna(subset=['Name'], inplace=True) # Drop the row with the null "Name".

**Release date**: We convert release date to a consistent format: YYYY-MM-DD and make sure that there are no errors, for example, 2028-20-41.

In [123]:
converted_dates = pd.to_datetime(df['Release date'], errors = 'coerce') # Convert release date to the default pandas format: datetime64[ns] displayed as YYYY-MM-DD
bad_dates = df[converted_dates.isna()] # Check for any NaT (Not a Time) values. 
print(bad_dates['Release date'].unique())

<StringArray>
[]
Length: 0, dtype: str

In [124]:
df['Release date'] = pd.to_datetime(df['Release date']) # Convert release date to the default pandas format: datetime64[ns] displayed as YYYY-MM-DD

years = df['Release date'].dt.year.unique().tolist() # Make sure the year of release falls within in the expected range
print(sorted(years))

months = df['Release date'].dt.month.unique().tolist() # Make sure the month of release falls within the expected range
print(sorted(months))

days = df['Release date'].dt.day.unique().tolist() # Make sure the day of release falls within the expected range 
print(sorted(days))

[1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

"Release date" is now in a consistent format and

**Feature Extraction**: We now create a few new useful features using the ones we already have. Note that we aren't necessarily aiming to reduce dimensionality of your dataset just yet.

**New Feature: Game age**: We create this new feature that will help us normalize revenue generated by a game per year later on. We require this feature to be in number of years accurate to two decimal places. Since every fourth year has 366 days, it will be slightly more appropriate to use a year as 365.25 days below. Please note that Game age is calculated with respect to the date this code was written: May 6, 2026. :)

In [125]:
from datetime import date

today = pd.Timestamp('2026-05-06')

df['Game age'] = ((today - df['Release date']) / pd.Timedelta(days = 365.25)).round(2)

Let us verify that this feature is producing the age of a game as expected. The game [Stardew Valley](https://store.steampowered.com/app/413150/Stardew_Valley/) came out in Feb, 2016, so the expected age of this game is a little more than 10 years.

In [126]:
print(df.loc[df['Name'] == 'Stardew Valley', 'Game age']) # The output below is as expected.

95881    10.19
Name: Game age, dtype: float64

**New Feature: Average owners**: This feature is a string that gives an estimated range of the number of owners of a game. We will use this range to get an estimate of the number of owners as one single number. In this case, we choose this estimate to be the mean of the range. The mean is a crude but appropriate measure of central tendency in this scenario. The main purpose of this feature is to estimate yearly revenue generated by a game.

In [127]:
# Split the 'Estimated owners' column into two temporary columns
owners_split = df['Estimated owners'].str.split('-', expand=True).astype(float)

# Calculate the average of the range owners_split[0] is the low end, owners_split[1] is the high end
df['Average owners'] = (owners_split[0] + owners_split[1]) / 2

**New Feature: Estimated Yearly Revenue**: We would like to get an estimate of the revenue generated per year by each game. To do this, we define Estimated revenue = (Average owners X Price) / Game age. We keep in mind the following facts about game pricing in mind:

1. Since "Price" is in USD, we are ignoring the fact that games are also bought by people outside the US using currencies different from the USD.
2. Many games go on discount a few times a year so the actual revenue generated is typically lower.
3. Steam takes a cut from the price a buyer pays for a game so the actual revenue a game developer generates is smaller. Similarly, several other "middle men" take their cut, for example, the game publisher, game promoters, etc.
4. There are "fremium" games. These games are free to download and play but may inlude paid additional content.
5. Many modern games have DLCs, i.e., domnloadble content which is typically paid and may generate revenue beyond the original purchase of the game. 
6. Lastly, the entries in the feature "Price" are proabably recorded at the time this dataset was created and the typical price of a game may fluctuate over time.
   
Of course, this is far from an ideal estimate, but nonetheless, "Estimated revenue" will give us an indication of how a paid game has performed financially. We keep in mind that "Estimated revenue" will typically be a gross upper bound of the actual revenue generated by the game.

In [128]:
df['Estimated revenue'] = (df['Average owners'] * df['Price']) / df['Game age']

Let's reorder the games by "Estimated revenue" in descending to see if we recognize some of the games and list out the top 20 games by yearly revenue. This seems like a more appropriate head for this dataset!

In [129]:
df = df.sort_values(by='Estimated revenue', ascending=False); # Sort the games by yearly revenue.

df = df.reset_index(drop = True) # Reset index 
df.index = df.index + 1

df.iloc[0:20, 1] # Let's see the top twenty games.

1              Black Myth: Wukong
2            Monster Hunter Wilds
3             New World: Aeternum
4                 Path of Exile 2
5                        Palworld
6                 Baldur's Gate 3
7                   HELLDIVERS™ 2
8                      Last Epoch
9                EA SPORTS FC™ 25
10                     ELDEN RING
11                   Satisfactory
12                  7 Days to Die
13              Battlefield™ 2042
14                     Schedule I
15                           SCUM
16                      CyberCorp
17                 Cyberpunk 2077
18    Clair Obscur: Expedition 33
19                 Battlefield™ V
20                       Hades II
Name: Name, dtype: str

## Categorical Featues

**New Feature: Language count**: We will use the feature "Supported languages" to create this new feature that gives the number of languages that a game supports. We keep in mind that these are languages whose *text* is dupported in the game, not necessarily the audio.

In [150]:
all_langs = []

for entry in df["Supported languages"].dropna():
    langs = [g.strip() for g in entry.split(",")]
    all_langs.extend(langs)

unique_langs = sorted(set(all_langs))
print(unique_langs)

["' Korean'", "'#lang_slovakian'", "'Afrikaans'", "'Afrikaans']", "'Albanian'", "'Albanian']", "'Amharic'", "'Arabic'", "'Arabic']", "'Armenian'", "'Armenian']", "'Assamese'", "'Azerbaijani'", "'Azerbaijani']", "'Bangla'", "'Bangla']", "'Basque'", "'Basque']", "'Belarusian'", "'Belarusian']", "'Bosnian'", "'Bosnian']", "'Bulgarian'", "'Bulgarian']", "'Catalan'", "'Catalan']", "'Cherokee'", "'Cherokee']", "'Croatian'", "'Croatian']", "'Czech'", "'Czech']", "'Danish'", "'Danish']", "'Dari'", "'Dutch'", "'Dutch']", "'English'", "'English']", "'Estonian'", "'Estonian']", "'Filipino'", "'Filipino']", "'Finnish'", "'Finnish']", "'French&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt;'", "'French'", "'French']", "'French[b][/b]'", "'Galician'", "'Galician']", "'Georgian'", "'Georgian']", "'German&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt;'", "'German'", "'German']", "'German;'", "'German[b][/b]'", "'Greek'", "'Greek']", "'Gujarati'", "'Hausa'", "'Hebrew'", "'Hebrew']", "'Hindi'", "'Hindi']", "'Hungarian", "'Hungarian'", "'Hungarian']", "'Icelandic'", "'Icelandic']", "'Igbo'", "'Igbo']", "'Indonesian'", "'Indonesian']", "'Irish'", "'Irish']", "'Italian \\r\\n\\r\\n[b][/b] ']", "'Italian&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt;'", "'Italian'", "'Italian']", "'Italian[b][/b]'", "'Japanese &amp;amp;amp;amp;lt;br /&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;br /&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt; ']", "'Japanese (all with full audio support)']", "'Japanese \\r\\n\\r\\n[b][/b] ']", "'Japanese'", "'Japanese']", "'Kannada'", "'Kazakh'", "'Kazakh']", "'Khmer'", "'Khmer']", "'Kinyarwanda'", "'Kinyarwanda']", "'Konkani'", "'Korean&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt;'", "'Korean'", "'Korean']", "'Korean[b][/b]'", "'Kyrgyz'", "'Kyrgyz']", "'Latvian'", "'Latvian']", "'Lithuanian'", "'Lithuanian']", "'Luxembourgish'", "'Luxembourgish']", "'Macedonian'", "'Macedonian']", "'Malay'", "'Malay']", "'Malayalam'", "'Malayalam']", "'Maltese'", "'Maori'", "'Maori']", "'Marathi'", "'Marathi']", "'Mongolian'", "'Mongolian']", "'Nepali'", "'Norwegian'", "'Norwegian']", "'Odia'", "'Persian'", "'Persian']", "'Polish'", "'Polish']", "'Portuguese - Brazil'", "'Portuguese - Brazil']", "'Portuguese - Portugal'", "'Portuguese - Portugal']", "'Punjabi (Gurmukhi)'", "'Punjabi (Gurmukhi)']", "'Punjabi (Shahmukhi)'", "'Punjabi (Shahmukhi)']", "'Quechua'", "'Quechua']", "'Romanian'", "'Romanian']", "'Russian'", "'Russian']", "'Russian\\r\\n[b][/b]']", "'Scots'", "'Scots']", "'Serbian'", "'Serbian']", "'Simplified Chinese'", "'Simplified Chinese']", "'Sindhi'", "'Sinhala'", "'Sinhala']", "'Slovak'", "'Slovak']", "'Slovenian'", "'Slovenian']", "'Sorani'", "'Sotho'", "'Spanish - Latin America'", "'Spanish - Latin America']", "'Spanish - Spain&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt;'", "'Spanish - Spain'", "'Spanish - Spain']", "'Spanish - Spain[b][/b]'", "'Spanish - Spain\\r\\n[b][/b]']", "'Swahili'", "'Swahili']", "'Swedish'", "'Swedish']", "'Tajik'", "'Tamil'", "'Tamil']", "'Tatar'", "'Tatar']", "'Telugu'", "'Telugu']", "'Thai'", "'Thai']", "'Tigrinya'", "'Tigrinya']", "'Traditional Chinese (text only)']", "'Traditional Chinese'", "'Traditional Chinese']", "'Tswana'", "'Turkish'", "'Turkish']", "'Turkmen'", "'Turkmen']", "'Ukrainian'", "'Ukrainian']", "'Urdu'", "'Urdu']", "'Uyghur'", "'Uyghur']", "'Uzbek'", "'Uzbek']", "'Valencian'", "'Valencian']", "'Vietnamese'", "'Vietnamese']", "'Welsh'", "'Welsh']", "'Wolof'", "'Xhosa'", "'Xhosa']", "'Yoruba'", "'Yoruba']", "'Zulu'", "'Zulu']", "'\\r\\nFrench'", "'\\r\\nGerman']", "K'iche'", "Polish'", "['Arabic'", "['Arabic']", "['Basque']", "['Bulgarian'", "['Bulgarian']", "['Catalan']", "['Croatian'", "['Czech'", "['Czech']", "['Danish'", "['Danish']", "['Dutch'", "['Dutch']", "['English (full audio)'", "['English Dutch  English']", "['English&amp;amp;amp;amp;lt;strong&amp;amp;amp;amp;gt;&amp;amp;amp;amp;lt;/strong&amp;amp;amp;amp;gt;'", "['English'", "['English']", "['English[b][/b]'", "['English\\r\\nRussian\\r\\nSpanish - Spain\\r\\nJapanese\\r\\nCzech']", "['Finnish'", "['Finnish']", "['French'", "['French']", "['German'", "['German']", "['Greek']", "['Hebrew']", "['Hungarian'", "['Indonesian']", "['Italian'", "['Italian']", "['Japanese'", "['Japanese']", "['Korean'", "['Korean']", "['Lithuanian'", "['Norwegian']", "['Polish'", "['Polish']", "['Portuguese - Brazil'", "['Portuguese - Brazil']", "['Portuguese - Portugal'", "['Portuguese - Portugal']", "['Romanian'", "['Romanian']", "['Russian'", "['Russian']", "['Russian\\r\\nEnglish\\r\\nSpanish - Spain\\r\\nFrench\\r\\nJapanese\\r\\nCzech']", "['Simplified Chinese'", "['Simplified Chinese']", "['Slovak'", "['Slovak']", "['Spanish - Latin America'", "['Spanish - Latin America']", "['Spanish - Spain'", "['Spanish - Spain']", "['Swedish']", "['Thai'", "['Thai']", "['Traditional Chinese'", "['Traditional Chinese']", "['Turkish'", "['Turkish']", "['Ukrainian'", "['Ukrainian']", "['Uzbek']", "['Vietnamese'", "['Vietnamese']", '[]']

We now take a look at "Genres", "Categories" and "Tags". These features are very important for constructing our recommender system. We see with a quick glance below that "Genres" looks fine but "Categories" and "Tags" deserves a closer look considering the large number of unique values it admits.

In [145]:
all_genres = []

for entry in df['Genres'].dropna():
    genres = [g.strip() for g in entry.split(",")]
    all_genres.extend(genres)

unique_genres = sorted(set(all_genres))
print(unique_genres)

['360 Video', 'Accounting', 'Action', 'Adventure', 'Animation & Modeling', 'Audio Production', 'Casual', 'Design & Illustration', 'Documentary', 'Early Access', 'Education', 'Episodic', 'Free To Play', 'Game Development', 'Gore', 'Indie', 'Massively Multiplayer', 'Movie', 'Nudity', 'Photo Editing', 'RPG', 'Racing', 'Short', 'Simulation', 'Software Training', 'Sports', 'Strategy', 'Tutorial', 'Utilities', 'Video Production', 'Violent', 'Web Publishing']

In [146]:
all_categories = []

for entry in df['Categories'].dropna():
    categories = [g.strip() for g in entry.split(",")]
    all_categories.extend(categories)

unique_categories = sorted(set(all_categories))
print(unique_categories)

['Adjustable Difficulty', 'Adjustable Text Size', 'Camera Comfort', 'Captions available', 'Chat Speech-to-text', 'Chat Text-to-speech', 'Co-op', 'Color Alternatives', 'Commentary available', 'Cross-Platform Multiplayer', 'Custom Volume Controls', 'Family Sharing', 'Full controller support', 'HDR available', 'In-App Purchases', 'Includes Source SDK', 'Includes level editor', 'Keyboard Only Option', 'LAN Co-op', 'LAN PvP', 'MMO', 'Mods', 'Mods (require HL2)', 'Mouse Only Option', 'Multi-player', 'Narrated Game Menus', 'Online Co-op', 'Online PvP', 'Partial Controller Support', 'Playable without Timed Input', 'PvP', 'Remote Play Together', 'Remote Play on Phone', 'Remote Play on TV', 'Remote Play on Tablet', 'Save Anytime', 'Shared/Split Screen', 'Shared/Split Screen Co-op', 'Shared/Split Screen PvP', 'Single-player', 'Stats', 'Steam Achievements', 'Steam Cloud', 'Steam Leaderboards', 'Steam Timeline', 'Steam Trading Cards', 'Steam Turn Notifications', 'Steam Workshop', 'SteamVR Collectibles', 'Stereo Sound', 'Subtitle Options', 'Surround Sound', 'Touch Only Option', 'Tracked Controller Support', 'VR Only', 'VR Support', 'VR Supported', 'Valve Anti-Cheat enabled']

Glancing over "Categories", we notice that most of it is fine except there are two entries "VR Supoort" and "VR Supported" that should be unfied to one: "VR Supported".

In [131]:
all_tags = []

for entry in df["Tags"].dropna():
    tags = [g.strip() for g in entry.split(",")]
    all_tags.extend(tags)

unique_tags = sorted(set(all_tags))
print(unique_tags)

['1980s', "1990's", '2.5D', '2D', '2D Fighter', '2D Platformer', '360 Video', '3D', '3D Fighter', '3D Platformer', '3D Vision', '4 Player Local', '4X', '6DOF', '8-bit Music', 'ATV', 'Abstract', 'Action', 'Action RPG', 'Action RTS', 'Action Roguelike', 'Action-Adventure', 'Addictive', 'Adventure', 'Agriculture', 'Aliens', 'Alternate History', 'Ambient', 'America', 'Animation & Modeling', 'Anime', 'Arcade', 'Archery', 'Arena Shooter', 'Artificial Intelligence', 'Assassin', 'Asymmetric VR', 'Asynchronous Multiplayer', 'Atmospheric', 'Audio Production', 'Auto Battler', 'Automation', 'Automobile Sim', 'BMX', 'Base-Building', 'Baseball', 'Based On A Novel', 'Basketball', 'Batman', 'Battle Royale', "Beat 'em up", 'Beautiful', 'Benchmark', 'Bikes', 'Birds', 'Blood', 'Board Game', 'Boomer Shooter', 'Boss Rush', 'Bowling', 'Boxing', 'Building', 'Bullet Hell', 'Bullet Time', 'CRPG', 'Capitalism', 'Card Battler', 'Card Game', 'Cartoon', 'Cartoony', 'Casual', 'Cats', 'Character Action Game', 'Character Customization', 'Chess', 'Choices Matter', 'Choose Your Own Adventure', 'Cinematic', 'City Builder', 'Class-Based', 'Classic', 'Clicker', 'Co-op', 'Co-op Campaign', 'Coding', 'Cold War', 'Collectathon', 'Colony Sim', 'Colorful', 'Combat', 'Combat Racing', 'Comedy', 'Comic Book', 'Competitive', 'Conspiracy', 'Controller', 'Conversation', 'Cooking', 'Cozy', 'Crafting', 'Creature Collector', 'Cricket', 'Crime', 'Crowdfunded', 'Cult Classic', 'Cute', 'Cyberpunk', 'Cycling', 'Dark', 'Dark Comedy', 'Dark Fantasy', 'Dark Humor', 'Dating Sim', 'Deckbuilding', 'Demons', 'Design & Illustration', 'Destruction', 'Detective', 'Dice', 'Difficult', 'Dinosaurs', 'Diplomacy', 'Documentary', 'Dog', 'Dragons', 'Drama', 'Driving', 'Dungeon Crawler', 'Dungeons & Dragons', 'Dwarf', 'Dynamic Narration', 'Dystopian', 'Early Access', 'Economy', 'Education', 'Electronic', 'Electronic Music', 'Elf', 'Emotional', 'Epic', 'Episodic', 'Escape Room', 'Experience', 'Experimental', 'Exploration', 'Extraction Shooter', 'FMV', 'FPS', 'Faith', 'Family Friendly', 'Fantasy', 'Farming', 'Farming Sim', 'Fast-Paced', 'Feature Film', 'Female Protagonist', 'Fighting', 'First-Person', 'Fishing', 'Flight', 'Football', 'Football (American)', 'Football (Soccer)', 'Foreign', 'Fox', 'Free to Play', 'Funny', 'Futuristic', 'Gambling', 'Game Development', 'GameMaker', 'Games Workshop', 'Gaming', 'God Game', 'Golf', 'Gore', 'Gothic', 'Grand Strategy', 'Great Soundtrack', 'Grid-Based Movement', 'Gun Customization', 'Hack and Slash', 'Hacking', 'Hand-drawn', 'Hardware', 'Heist', 'Hentai', 'Hero Shooter', 'Hex Grid', 'Hidden Object', 'Historical', 'Hobby Sim', 'Hockey', 'Horror', 'Horses', 'Hunting', 'Idler', 'Illuminati', 'Immersive', 'Immersive Sim', 'Indie', 'Instrumental Music', 'Intentionally Awkward Controls', 'Interactive Fiction', 'Inventory Management', 'Investigation', 'Isometric', 'JRPG', 'Jet', 'Job Simulator', 'Jump Scare', 'Kickstarter', 'LEGO', 'LGBTQ+', 'Lara Croft', 'Lemmings', 'Level Editor', 'Life Sim', 'Linear', 'Local Co-Op', 'Local Multiplayer', 'Logic', 'Loot', 'Looter Shooter', 'Lore-Rich', 'Lovecraftian', 'MMORPG', 'MOBA', 'Magic', 'Mahjong', 'Management', 'Mars', 'Martial Arts', 'Massively Multiplayer', 'Masterpiece', 'Match 3', 'Mature', 'Mechs', 'Medical Sim', 'Medieval', 'Memes', 'Metroidvania', 'Military', 'Mini Golf', 'Minigames', 'Minimalist', 'Mining', 'Mod', 'Moddable', 'Modern', 'Motocross', 'Motorbike', 'Mouse only', 'Movie', 'Multiplayer', 'Multiple Endings', 'Music', 'Music-Based Procedural Generation', 'Musou', 'Mystery', 'Mystery Dungeon', 'Mythology', 'NSFW', 'Narration', 'Narrative', 'Nature', 'Naval', 'Naval Combat', 'Ninja', 'Noir', 'Nonlinear', 'Nostalgia', 'Nudity', 'Offroad', 'Old School', 'On-Rails Shooter', 'Online Co-Op', 'Open World', 'Open World Survival Craft', 'Otome', 'Outbreak Sim', 'Parkour', 'Parody', 'Party', 'Party Game', 'Party-Based RPG', 'Perma Death', 'Philosophical', 'Photo Editing', 'Physics', 'Pinball', 'Pirates', 'Pixel Graphics', 'Platformer', 'Point & Click', 'Political', 'Political Sim', 'Politics', 'Pool', 'Post-apocalyptic', 'Precision Platformer', 'Procedural Generation', 'Programming', 'Psychedelic', 'Psychological', 'Psychological Horror', 'Puzzle', 'Puzzle-Platformer', 'PvE', 'PvP', 'Quick-Time Events', 'RPG', 'RPGMaker', 'RTS', 'Racing', 'Real Time Tactics', 'Real-Time', 'Real-Time with Pause', 'Realistic', 'Reboot', 'Relaxing', 'Remake', 'Replay Value', 'Resource Management', 'Retro', 'Rhythm', 'Robots', 'Rock Music', 'Rogue-like', 'Rogue-lite', 'Roguelike Deckbuilder', 'Roguevania', 'Romance', 'Rome', 'Rugby', 'Runner', 'Sailing', 'Sandbox', 'Satire', 'Sci-fi', 'Science', 'Score Attack', 'Sequel', 'Sexual Content', "Shoot 'Em Up", 'Shooter', 'Shop Keeper', 'Short', 'Side Scroller', 'Silent Protagonist', 'Simulation', 'Singleplayer', 'Skateboarding', 'Skating', 'Skiing', 'Sniper', 'Snooker', 'Snow', 'Snowboarding', 'Social Deduction', 'Software', 'Software Training', 'Sokoban', 'Solitaire', 'Souls-like', 'Soundtrack', 'Space', 'Space Sim', 'Spaceships', 'Spectacle fighter', 'Spelling', 'Split Screen', 'Sports', 'Stealth', 'Steam Machine', 'Steampunk', 'Story Rich', 'Strategy', 'Strategy RPG', 'Stylized', 'Submarine', 'Superhero', 'Supernatural', 'Surreal', 'Survival', 'Survival Horror', 'Swordplay', 'Tabletop', 'Tactical', 'Tactical RPG', 'Tanks', 'Team-Based', 'Tennis', 'Text-Based', 'Third Person', 'Third-Person Shooter', 'Thriller', 'Tile-Matching', 'Time Attack', 'Time Management', 'Time Manipulation', 'Time Travel', 'Top-Down', 'Top-Down Shooter', 'Touch-Friendly', 'Tower Defense', 'TrackIR', 'Trading', 'Trading Card Game', 'Traditional Roguelike', 'Trains', 'Transhumanism', 'Transportation', 'Trivia', 'Turn-Based', 'Turn-Based Combat', 'Turn-Based Strategy', 'Turn-Based Tactics', 'Tutorial', 'Twin Stick Shooter', 'Typing', 'Underground', 'Underwater', 'Unforgiving', 'Utilities', 'VR', 'VR Only', 'Vampire', 'Vehicular Combat', 'Video Production', 'Vikings', 'Villain Protagonist', 'Violent', 'Visual Novel', 'Voice Control', 'Volleyball', 'Voxel', 'Walking Simulator', 'War', 'Wargame', 'Warhammer 40K', 'Web Publishing', 'Well-Written', 'Werewolves', 'Western', 'Wholesome', 'Word Game', 'World War I', 'World War II', 'Wrestling', 'Zombies', 'e-sports']

**New Feature**: Website: It gives the URL of the Steam webpage of a game. We use the feature "AppID" to construct this feature, which contains no NaN objects, so we are ready to use it. This is the correct way to record a game's Steam URL. Steam uses a consistent URL format for all games as outlined in the code below.

In [132]:
df['Website'] = 'https://store.steampowered.com/app/' + df['AppID'].astype(str) + '/' 
df.loc[df['Name'] == 'The Talos Principle', 'Website'] # The feature works as intended. Go ahead and check our this game by clicking the link below. It's awesome!

2656    https://store.steampowered.com/app/257510/
Name: Website, dtype: str

In [133]:
((df['Positive'] == 0) & (df['Negative'] == 0)).sum()

np.int64(39661)

**New Feature: Vote Percent**: This feature gives the percentage of positive votes. We use the features "Positive" and "Negative" to do this. This operation will return NaN precisely when there are no positive or negative votes. In this case, we will set the vote percent of such a game to 0.

In [134]:
df['Vote percent'] = df['Positive'] / (df['Positive'] + df['Negative']) * 100

In [135]:
df['Vote percent'].isnull().sum()

np.int64(39661)

In [136]:
df['Vote percent'] = df['Vote percent'].fillna(0) # Let's set NaN values to 0. We'll use Bayesian statsitics to rigorously address this later.

As an example, let's check the Vote percent of the game [Stardew Valley](https://store.steampowered.com/app/413150/Stardew_Valley/). It's identical (rounded to the closest integer) to what you'll see on the Steam webpage for the game.

In [138]:
df.loc[df['Name'] == 'Stardew Valley', 'Vote percent']

78    98.441539
Name: Vote percent, dtype: float64

### Removing games with undesired elements

We now work on the rows and start by removing games that contain undesired elements. We do this performing a word search and then changing our dataframe to leave those games alone that do NOT contain these words.

In [139]:
# Words we wish to search
words = 'extreme violence|torture|intercourse|prostitution|pornography|pornographic|hentai|masturbation|sexual content'

# Search these words across relevant features
nope_words = (df['About the game'].str.contains(words, case=False, na=False)) | \
       (df['Reviews'].str.contains(words, case=False, na=False)) | \
       (df['Notes'].str.contains(words, case=False, na=False)) | \
       (df['Genres'].str.contains(words, case=False, na=False)) | \
       (df['Categories'].str.contains(words, case=False, na=False)) | \
       (df['Tags'].str.contains(words, case=False, na=False)) 
       
df = df[~nope_words]

In [140]:
df.shape

(114452, 27)

**Dropping Features**

1. **Reviews and Notes**: Now that they've been used to drop undesired games, their purpose is exhausted. They can arguably be mined for keywords that can be useful for a recommendation engine, but the features "Categories" and "Tags" do exactly that and are arguably more reliable since they are driven by user feedback.
2. **Recommendations**: Gives the number of recommendations a game has received across Steam's community features using the outdated Steamworks API. As we see below, this feature is very rare: about 83% values are zero. We also see that for the most popular games, this feature is highly (Pearson) correlated with "Positive". Lastly, the non-zero values of this features starts off at 101, which is rather curious. As such we drop this feature in favor of the more robust "Positive" which has already been used above to create "Vote percent".

In [141]:
n = ((df['Recommendations'] == 0).sum() / df.shape[0]) * 100            # About 84% of "Recommendations" is 0. 
print(f"The percentage of games with zero Recommendations is {n}.")
print(sorted(df['Recommendations'].unique())[:5])      # Notice that the non-zero recommendations start at 101.

The percentage of games with zero Recommendations is 83.94086603991194.
[np.int64(0), np.int64(101), np.int64(102), np.int64(103), np.int64(104)]

In [142]:
# Calculate both correlation matrices

pearson_corr = df['Positive'].corr(df['Recommendations'], method='pearson')
spearman_corr = df['Positive'].corr(df['Recommendations'], method='spearman')

print(f"Pearson Correlation (Linear): {pearson_corr:.4f}")
print(f"Spearman Correlation (Rank): {spearman_corr:.4f}")

Pearson Correlation (Linear): 0.9017
Spearman Correlation (Rank): 0.5409

In [143]:
df =df.drop(columns = ['Notes', 'Reviews', 'Recommendations'])

In [144]:
df.info()

<class 'pandas.DataFrame'>
Index: 114452 entries, 1 to 122610
Data columns (total 24 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   AppID                     114452 non-null  int64
 1   Name                      114452 non-null  str
 2   Release date              114452 non-null  datetime64[us]
 3   Estimated owners          114452 non-null  str
 4   Peak CCU                  114452 non-null  int64
 5   Price                     114452 non-null  float64
 6   DLC count                 114452 non-null  int64
 7   About the game            106017 non-null  str
 8   Supported languages       114452 non-null  str
 9   Header image              114375 non-null  str
 10  Positive                  114452 non-null  int64
 11  Negative                  114452 non-null  int64
 12  Average playtime forever  114452 non-null  int64
 13  Median playtime forever   114452 non-null  int64
 14  Developers                106018 non-null  str
 15  Publishers                105572 non-null  str
 16  Categories                105518 non-null  str
 17  Genres                    106080 non-null  str
 18  Tags                      79119 non-null   str
 19  Game age                  114452 non-null  float64
 20  Average owners            114452 non-null  float64
 21  Estimated revenue         114452 non-null  float64
 22  Website                   114452 non-null  str
 23  Vote percent              114452 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(7), str(11)
memory usage: 21.8 MB

In [97]:
df = df.reset_index(drop = True)
df.index = df.index + 1

In [98]:
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Price,DLC count,About the game,Supported languages,Header image,...,Developers,Publishers,Categories,Genres,Tags,Game age,Average owners,Estimated revenue,Website,Vote percent
1,2358720,Black Myth: Wukong,2024-08-19,50000000 - 100000000,15004,59.99,2,Black Myth: Wukong is an action RPG rooted in ...,"['English', 'French', 'German', 'Spanish - Spa...",https://shared.akamai.steamstatic.com/store_it...,...,Game Science,Game Science,"Single-player,Steam Achievements,Full controll...","Action,Adventure,RPG","Mythology,Action RPG,Action,Souls-like,RPG,Com...",1.71,75000000.0,2.631140e+09,https://store.steampowered.com/app/2358720/,96.663067
2,2246340,Monster Hunter Wilds,2025-02-27,20000000 - 50000000,12494,38.49,190,The unbridled force of nature runs wild and re...,"['English', 'French', 'Italian', 'German', 'Sp...",https://shared.akamai.steamstatic.com/store_it...,...,"CAPCOM Co., Ltd.","CAPCOM Co., Ltd.","Single-player,Multi-player,Co-op,Online Co-op,...","Action,Adventure,RPG","Hunting,Action,Multiplayer,Online Co-Op,Co-op,...",1.19,35000000.0,1.132059e+09,https://store.steampowered.com/app/2246340/,58.271181
3,2694490,Path of Exile 2,2024-12-06,20000000 - 50000000,16727,29.99,9,Path of Exile 2 is a next generation Action RP...,"['English', 'French', 'German', 'Spanish - Spa...",https://shared.akamai.steamstatic.com/store_it...,...,Grinding Gear Games,Grinding Gear Games,"Single-player,Multi-player,MMO,Co-op,Online Co...","Action,Adventure,Massively Multiplayer,RPG,Ear...","Action RPG,Hack and Slash,RPG,Souls-like,MMORP...",1.41,35000000.0,7.444326e+08,https://store.steampowered.com/app/2694490/,70.116139
4,1623730,Palworld,2024-01-18,50000000 - 100000000,18028,22.49,1,"Q. What kind of game is this? A. In this game,...","['English', 'Simplified Chinese', 'Traditional...",https://shared.akamai.steamstatic.com/store_it...,...,Pocketpair,Pocketpair,"Single-player,Multi-player,Co-op,Online Co-op,...","Action,Adventure,Indie,RPG,Early Access","Open World,Survival,Creature Collector,Multipl...",2.30,75000000.0,7.333696e+08,https://store.steampowered.com/app/1623730/,94.104946
5,553850,HELLDIVERS™ 2,2024-02-08,20000000 - 50000000,53399,31.99,1,The Galaxy’s Last Line of Offence. Enlist in t...,"['English', 'French', 'Italian', 'German', 'Sp...",https://shared.akamai.steamstatic.com/store_it...,...,Arrowhead Game Studios,PlayStation Publishing LLC,"Multi-player,Co-op,Online Co-op,Steam Achievem...",Action,"Online Co-Op,PvE,Third-Person Shooter,Multipla...",2.24,35000000.0,4.998437e+08,https://store.steampowered.com/app/553850/,76.243742

# Business

## Revenue Estimation

We would like to get an estimate of revenue generated by each game. To do this, we define Estimated revenue = Estimated owners X Price. In doing so, we are making several assumptions:

1. Since "Price" is in USD, we are ignoring the fact that games are also bought by people outside the US using currencies different from the USD.
2. Many games go on discount a few times a year so the actual revenue generated is typically lower.
3. Steam takes a cut from the price a buyer pays for a game so the actual revenue a game developer generates is smaller. Similarly, several other "middle men" take their cut, for example, the game publisher, game promoters, etc.
4. There are "fremium" games
5. Lastly, the entries in the feature "Price" are proabably recorded at the time this dataset was created and the typical price of a game may fluctuate over time.
   
Of course, this is far from an ideal estimate, but nonetheless, "Estimated revenue" will give us an indication of how a paid game has performed financially. We keep in mind that "Estimated revenue" will typically be a gross upper bound of the actual revenue generated by the game.

df['Estimated owners'].unique()

First note that "Estimated owners" is a string-type range. We will create a new feature "Average owners" by converting a given range to an integer by taking the midpoint of each range. For example, the range 50,000 - 100,000 will be converted to the integer 75,000.

In [44]:
# Split the 'Estimated owners' column into two temporary columns
owners_split = df['Estimated owners'].str.split('-', expand=True).astype(float)

# Calculate the average of the range owners_split[0] is the low end, owners_split[1] is the high end
df['Average owners'] = (owners_split[0] + owners_split[1]) / 2

# Multiply by Price to get Estimated revenue
df['Estimated revenue'] = df['Average owners'] * df['Price']

Let's reorder the games by "Estimated revenue" in descending to see if we recognize some of the games. This seems like a much better head for this dataset!

In [45]:
df = df.sort_values(by='Estimated revenue', ascending=False);
df.iloc[0:20, 0]

1     2358720
5     1623730
10    1245620
2     2246340
7      553850
4     2694490
8      899770
13    1517290
17    1091500
32     252490
9     2669320
59     374320
41     814380
11     526870
26     261550
12     251570
64     346110
57     221100
78     413150
51    1238840
Name: AppID, dtype: int64

## Visualizing the most successful genres 

Let's look at the genres of the top 1% games by estimated revenue. We do this by creating a word bubble to visualize which genres appear most often for this top 1% category. This will give us an idea of which genres perform well financially. We start by looking at the data contained in the "Genres" feature more closely.

df.shape

df.iloc[0:5, 29:30]

Let's create a new dataframe (called top_1_percent) that contains the top 1% of our main dataframe. Then we'll first look at all the genres of the top 1% of the games.

top_1_percent = df.head(int(len(df) * 0.01))

all_genres = []

for entry in top_1_percent["Genres"].dropna():
    #genres = [g.strip() for g in entry.split(",")]
    #all_genres.extend(genres)

unique_genres = sorted(set(all_genres))
print(unique_genres)

Now we move on to create the Word Cloud.

from collections import Counter
import ast
import matplotlib.patches as mpatches
import numpy as np
from wordcloud import WordCloud

genre_counts = Counter(all_genres)

wc = WordCloud(
    width=1200,
    height=800,
    background_color="white",
    colormap="tab10",       # a colormap with distinct colors per genre
    max_words=50            # limit to top 50 genres if there are many
)

wc.generate_from_frequencies(genre_counts)

plt.figure(figsize=(14, 9))
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.title("Top 1% Games by Revenue — Genre Distribution", fontsize=18, pad=20)
plt.tight_layout()
plt.show()

This is a nice visual resprentation genres most successful by revenue. However, to be more analytically rigorous, let's use a bar chart to represent the game data - since our data ("Genres") is of categorical type, a bar chart is more approproate than a histogram.

# Count already done from before, just convert to a sorted DataFrame for plotting
genre_df = pd.DataFrame(genre_counts.most_common(), columns=["Genre", "Count"])

# Plot
plt.figure(figsize=(14, 8))
plt.bar(genre_df["Genre"], genre_df["Count"], color="midnightblue", edgecolor="white")

plt.title("Genre Frequency — Top 1% Games by Revenue", fontsize=16, pad=15)
plt.xlabel("Genre", fontsize=12)
plt.ylabel("Number of Games", fontsize=12)
plt.xticks(rotation=45, ha="right", fontsize=10)
plt.tight_layout()
plt.show()

However, note that the above distribution is not an accurate description of the success of a genre. The reason is that there are typically far more "Action" games than "Racing" games so it makes sense that the "Action" tag appears more often in the distribution. Therefore, we'll take the number of games with the tag "Action" and

This is excellent! We keep in mind that genres are not mutualy exclusive. A single game typically has multiple genres. Let's draw some elementary conclusions. 

1. Nearly 750 games out of 1195 games contain the Genre "Action".
2. The top 1% of the games don't contain many games with the genres "Sports" or "Racing". This may signal an opportunity (and a need) to make these games more popular.
3. About 100 games are "Early Access". These are games that are made available to purchase and play before their development is complete. That's about 8.3% of the top 1% of the games.

Now let's address those rows that have way too many NaN or null values.

print(df['Name'].duplicated().sum())

These duplicates mainly fall under one these cases:

1. Different versions of the base game. Some examples: Game of the Year Edition, Extended Edition, Developer's cut, etc.
2. A foreign language verison of the game that was released disjoint from the initial version.
3. Actual duplicates. 


We now prescribe criteria which will determine which of these duplicates must be removed. We must also remove the column "Achievements".

# Science: Recommendation System 

In this final chapter of this project, we will construct a recommendation system. A user will input a video game's name and the system will output a few games that the user is likely to enjoy. Our recommendation system is content-based. This means that it uses the features of an input to recommend new content. 

## The recommendation system has three very important features:
1. In addition to suggesting five games that the user is likely to enjoy, the system also recommends three games that are "less" similar than the first 5. These latter three games raise the odds of discovering a "hidden gem".
2. At least one recommended game is free to play!
3. In the event the user inputs a game that does not exist in our dataset, the system will prompt the user to try again by suggesting a few popular games from the database that the user is likely to know. In addition, it will display an inforgraphic that shows certain statistics of genres and categories. This helps address one aspect of cold start problem. 

## Architecture of the recommendation system:
We use $k$-means clustering to create clusters where games within one cluster are similar in genre and "feel". Then we use $k$-nearest neighbors to select games within a given cluster.